// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cinematch_back.Data;

#nullable disable

namespace cinematch_back.Migrations
{
    [DbContext(typeof(CinematchDBContext))]
    [Migration("20240621224926_AddDurationMovieTable")]
    partial class AddDurationMovieTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cinematch_back.Models.AgeModel", b =>
                {
                    b.Property<int>("IDAge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDAge"));

                    b.Property<string>("Age")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDAge");

                    b.ToTable("TBLAge");
                });

            modelBuilder.Entity("cinematch_back.Models.DurationModel", b =>
                {
                    b.Property<int>("IDDuration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDDuration"));

                    b.Property<string>("DurationMovie")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDDuration");

                    b.ToTable("TBLDurationMovie");
                });

            modelBuilder.Entity("cinematch_back.Models.EndModel", b =>
                {
                    b.Property<int>("IDEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDEnd"));

                    b.Property<string>("End")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDEnd");

                    b.ToTable("TBLEnd");
                });

            modelBuilder.Entity("cinematch_back.Models.GenreModel", b =>
                {
                    b.Property<int>("IDGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDGenre"));

                    b.Property<string>("Genre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDGenre");

                    b.ToTable("TBLGenres");
                });

            modelBuilder.Entity("cinematch_back.Models.KindModel", b =>
                {
                    b.Property<int>("IDKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDKind"));

                    b.Property<string>("Kind")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDKind");

                    b.ToTable("TBLKind");
                });

            modelBuilder.Entity("cinematch_back.Models.StoryTypeModel", b =>
                {
                    b.Property<int>("IDStoryType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDStoryType"));

                    b.Property<string>("StoryType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDStoryType");

                    b.ToTable("TBLStoryType");
                });

            modelBuilder.Entity("cinematch_back.Models.TestModel", b =>
                {
                    b.Property<int>("IDTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDTest"));

                    b.Property<string>("Teste")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDTest");

                    b.ToTable("TBLTestes");
                });
#pragma warning restore 612, 618
        }
    }
}
